services:
  adnd2e-private:
    restart: unless-stopped
    container_name: adnd2e-private
    image: node:18-alpine # Or use a dedicated Docusaurus image
    hostname: adnd2e-private
    ports:
      - "3030:3030"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.adnd2e-private-http.entrypoints: web
      traefik.http.routers.adnd2e-private-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.adnd2e-private-http.rule: Host(`adnd2e-private.mayorgergich.xyz`)
      traefik.http.routers.adnd2e-private-http.service: adnd2e-private
      traefik.http.routers.adnd2e-private.entrypoints: websecure
      # Add Authelia authentication middleware here
      traefik.http.routers.adnd2e-private.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker,authelia@file
      traefik.http.routers.adnd2e-private.rule: Host(`adnd2e-private.mayorgergich.xyz`)
      traefik.http.routers.adnd2e-private.service: adnd2e-private
      traefik.http.routers.adnd2e-private.tls.certresolver: cfdns
      traefik.http.routers.adnd2e-private.tls.options: securetls@file
      traefik.http.services.adnd2e-private.loadbalancer.server.port: 3030
    volumes:
      - /opt/adnd2e-private:/app
      - /etc/localtime:/etc/localtime:ro
    command: >
      sh -c "cd /app && 
      npm install && 
      mkdir -p docs/reference/classes docs/reference/races docs/reference/spells/wizard docs/reference/spells/priest docs/reference/proficiencies && 
      npm run build && 
      npm run serve -- --port 3030"

networks:
  saltbox:
    external: true
