version: "3.8"

services:
  adnd2e-private:
    image: private
    container_name: adnd2e-private
    hostname: adnd2e-private
    restart: unless-stopped
    environment:
      - private_DB_TYPE=mysql
      - private_DB_HOST=mariadb
      - private_DB_NAME=saltbox
      - private_DB_USER=pawneemayor
      - private_DB_PASSWORD=password321
    volumes:
      - /opt/adnd2e-private/images:/var/www/html/images
      - /opt/adnd2e-private/LocalSettings.php:/var/www/html/LocalSettings.php
      - /etc/localtime:/etc/localtime:ro
    command: apache2-foreground
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.adnd2e-private-http.entrypoints: web
      traefik.http.routers.adnd2e-private-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.adnd2e-private-http.rule: Host(`adnd2e-private.mayorgergich.xyz`)
      traefik.http.routers.adnd2e-private-http.service: adnd2e-private
      traefik.http.routers.adnd2e-private.entrypoints: websecure
      traefik.http.routers.adnd2e-private.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker,authelia@file
      traefik.http.routers.adnd2e-private.rule: Host(`adnd2e-private.mayorgergich.xyz`)
      traefik.http.routers.adnd2e-private.service: adnd2e-private
      traefik.http.routers.adnd2e-private.tls.certresolver: cfdns
      traefik.http.routers.adnd2e-private.tls.options: securetls@file
      traefik.http.services.adnd2e-private.loadbalancer.server.port: 80

networks:
  saltbox:
    external: true
