/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, all docs are included in the main "docs" sidebar
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    }
  ],
  
  // Character sidebar
  characterSidebar: [
    {
      type: 'autogenerated',
      dirName: 'character',
    }
  ],
  
  // Campaigns sidebar
  campaignsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'campaigns',
    }
  ],
  
  // Tactics sidebar
  tacticsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tactics',
    }
  ]
};

module.exports = sidebars;