/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, all docs are included in the main "docs" sidebar
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    }
  ],
  
  // Character sidebar
  characterSidebar: [
    {
      type: 'autogenerated',
      dirName: 'character',
    }
  ],
  
  // Campaigns sidebar
  campaignsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'campaigns',
    }
  ],
  
  // Tactics sidebar
  tacticsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tactics',
    }
  ],

  // Reference sidebar for imported content from adnd2e.fandom.com
  referenceSidebar: [
    {
      type: 'doc',
      id: 'reference/index',
      label: 'AD&D 2E Reference',
    },
    {
      type: 'category',
      label: 'Character Creation',
      items: [
        'reference/classes/index',
        'reference/races/index',
        'reference/proficiencies/index',
      ],
    },
    {
      type: 'category',
      label: 'Spells',
      items: [
        'reference/spells/wizard/index',
        'reference/spells/priest/index',
      ],
    },
  ],
};

module.exports = sidebars;